Configured TreeTagger to work with english models.

diff --git a/tools/treetagger/shal-eng b/tools/treetagger/shal-eng
--- a/tools/treetagger/shal-eng
+++ b/tools/treetagger/shal-eng
@@ -1,10 +1,20 @@
 #!/bin/sh
 
+# For the purpose of SHALMANESER, disable the normal TreeTagger tokenisation
 # Set these paths appropriately
 
-BIN=/proj/llx/Software/shalmaneser1.2/program/tools/treetagger/bin
-CMD=/proj/llx/Software/shalmaneser1.2/program/tools/treetagger/cmd
-LIB=/proj/llx/Software/shalmaneser1.2/program/tools/treetagger/lib
+command -v realpath >/dev/null 2>&1 || {
+    echo >&2 "I require <realpath> but it's not installed.  Aborting."
+    exit 1
+}
+
+BASE_DIR=$(dirname $(realpath $0))
+
+#BASE_DIR=/home/arbox/work_space/shalm/dev/program_de/tools/treetagger
+
+BIN=${BASE_DIR}/bin
+CMD=${BASE_DIR}/cmd
+LIB=${BASE_DIR}/lib
 
 TOKENIZER=${BIN}/separate-punctuation
 TAGGER=${BIN}/tree-tagger
